### ISSUE TITLE
How to have custom post-init logic/carry state in LanguageServer

### ISSUE THREAD

**Issue by artempyanykh** [silvanshade/lspower#8]
Use-case:
1. During initialization I build some context for the language server, e.g. root URI, experimental capabilities, ... (init context)
2. When this is done I need to scan the workspace, read files, handle ignores, etc. (post-init). I don't want this to be a part of `initialize` request handler and delay the initialize response, would rather do this in the background.
3. Then I'm ready to handle requests from the client, but to handle requests I need the information from steps 1 and 2.

All provided examples operate on:
```
struct Backend {
  client: Client
}

impl LanguageServer for Backend {
...
}
```

One idea was to add some additional fields to `Backend` to carry the extra context, but all methods from `LanguageServer` use `&self` as non-mut, so I'd have to use internal mutability which is not desirable. Also, it's not clear how to dispatch the _post-init_ step.

I thought maybe I could get around this at the `Service` or `Layer` level, but `LspService` doesn't provide access to the internal `LanguageServer`.

Am I missing something in the API that would allow me to have the desired behaviour?

**Comment by hvithrafn** [comment]
> 2\. When this is done I need to scan the workspace, read files, handle ignores, etc. (post-init). I don't want this to be a part of `initialize` request handler and delay the initialize response, would rather do this in the background.

Okay, there are a few things to consider here.

According to the spec, the idea behind the `initialize` request is that, until the server responds, the client should not send any additional requests or notifications to the server.

If the server responds to the `initialize` request early (before the data from step 2 has been computed), that means the client will likely end up making some requests that the server cannot respond to yet. Dealing that appropriately will entail implementing special logic in all the different request handlers and returning empty or null results if things aren't ready.

It may not be worth the additional complexity unless step 2 takes a long time on average or unless you don't expect to need all of that data to handle most of the standard requests.

> One idea was to add some additional fields to `Backend` to carry the extra context, but all methods from `LanguageServer` use `&self` as non-mut, so I'd have to use internal mutability which is not desirable.

Generally the idea here is that, because fields for `Backend` need to be synchronized between async requests, they will already be wrapped in `Mutex`, `RwLock`, or similar, and you use that for mutability. For instance:

```rust
pub struct PostInitData {
  // ..
}

pub struct Session {
    pub post_init_data: RwLock<Option<PostInitData>>,
}

pub struct Server {
    pub client: lspower::Client,
    pub session: Arc<Session>,
}

#[lspower::async_trait]
impl lspower::LanguageServer for Server {
    async fn initialize(&self, params: lsp::InitializeParams) -> jsonrpc::Result<lsp::InitializeResult> {
        *self.session.post_init_data.write().await = Some(computePostInitData(params));
        // ...
    }
}
```

> Also, it's not clear how to dispatch the post-init step.

There are a few options for this. You could use something like `tokio::spawn`, which would allow the request handler to complete while the computation runs in the background. The `RwLock` or `Mutex` will handle the synchronization appropriately:

```rust
    async fn initialize(&self, params: lsp::InitializeParams) -> jsonrpc::Result<lsp::InitializeResult> {
        tokio::spawn({
            let params = params.clone();
            let session = self.session.clone();
            async move {
                *session.post_init_data.write().await = Some(computePostInitData(params));
            }
        });
        // ...
    }
```

With this approach, you still have to implement custom logic in the various request handlers for the case when the data is not yet computed.

Another possibility would be to make `session.post_init_data` into a [`Shared`](https://docs.rs/futures/0.3.13/futures/future/struct.Shared.html) future. Something like this:

```rust
    async fn initialize(&self, params: lsp::InitializeParams) -> jsonrpc::Result<lsp::InitializeResult> {
        // assuming `computePostInitData` returns a future
        *session.post_init_data.write().await = computePostInitData(params).shared();
        // ...
    }
```

You would then access the field in an `async fn` with `self.session.post_init_data.read().await.await` (the second `await` for the shared future). You could make that a little nicer with a custom method.

With this approach, you could cause additional requests to essentially pause when they access the `post_init_data` field until it is been computed. But, again, unless you don't need this data for most requests, it's not clear you really gain much doing this since you could have just blocked on `initialize`.

Hope that helps.

**Comment by artempyanykh** [comment]
This is very-very helpful @silvanshade! Thanks for taking the time to write this.

One more question if I may -- say, I want to do something before or after each request from the client (like checking and publishing diagnostics or sending a status notification). First thing I thought about is to use a Layer for this -- basically, to implement this logic as a middleware. But with lspower, `LspService` doesn't give access to the underlying `LanguageService` impl. and hence to the `Client`. So, I wonder what's the intended way to implement this sort of functionality.

**Comment by silvanshade** [comment]
> So, I wonder what's the intended way to implement this sort of functionality.

Good question. Although it would probably be possible to do this through `Layer`, and although in theory that would probably involve less code duplication, that feels to me like the wrong level of abstraction, especially since more internals would need to be exposed in order to get that to work.

I think the best solution is to just factor your request handling logic in such a way that there is common functionality for triggering diagnostics and whatever else you need. So for instance, you might have something like this:

```rust
    async fn did_open(&self, params: lsp::DidOpenTextDocumentParams) {
        handle_did_open(session.clone(), params).await;
        handle_diagnostics(session.clone()).await;
    }

    async fn did_change(&self, params: lsp::DidChangeTextDocumentParams) {
        handle_did_change(session.clone(), params).await;
        handle_diagnostics(session.clone()).await;
    }
```

So I think this is really just an architecture design issue, i.e., building your handlers and structuring everything to where you can run whatever additional functions around the main requests that you need.

**Comment by artempyanykh** [comment]
Ok, this makes sense. Thank you very much @silvanshade! Let me close this issue now.
